# fly.toml app configuration file generated for discord-purple-cloud-8641 on 2025-11-07T23:05:32+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'discord-purple-cloud-8641'
primary_region = 'fra'


[processes]
  app = "python bot.py"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
