# fly.toml app configuration file generated for discord-small-glade-3749 on 2025-11-07T19:58:44+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

# ... (linie komentarza)
app = 'discord-small-glade-3749'
primary_region = 'gru'

[build]
  builder = 'paketobuildpacks/builder:base'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1